### ISSUE TITLE
name the user based on $USER

### ISSUE THREAD

**Issue by dougcole** [estately/vagrant-devbox#9]
Seems doable and then deploys call out the correct user and ssh'ing is potentially simpler if you have the same username.

**Comment by norman** [comment]
I would love this. I tried to set this up before and it was surprisingly painful. The first time you run `vagrant up` it needs to be using the default user from the base box. You'd have to set up two provisioning steps, so the first one brings the box up and adds the desired user and then logs out. Then the second step would log in with the new user and continue on. The simplest way to do this might be wrapping the VM creation in a rake task, since I don't think we could accomplish this with just `vagrant up`.

**Comment by phiggins** [comment]
What if we added something to the deployment script to read a local, gitignore'd file or something? The same problem would happen, for example, if two developers had the same user name.

**Comment by norman** [comment]
It does already has support for a personalized `playbook.local.yml`. I use that to set up my various quirky shell aliases.

**Comment by dougcole** [comment]
Ooooh. Here's my new idea - deploy names can be based on the output of `git config user.name`

**Comment by norman** [comment]
> Ooooh. Here's my new idea - deploy names can be based on the output of git config user.name

Awesome! That would be great.

**Comment by dougcole** [comment]
I'm calling this fixed. 👍
